# Generated by Django 4.1.4 on 2022-12-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
